import Head from "next/head";
import React from "react";
import Sidebar from "./Sidebar";

export default function Layout({ children, title }) {
  return (
    <div>
      <Head>
        <title>Nutriña{title ? `| ${title}` : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen flex flex-row justify-start">
        <Sidebar />
        <div className="bg-white flex-1 p-8 text-black">{children}</div>
      </div>
    </div>
  );
}
